version: '3'

services:
    zm-db:
        container_name: zm-db
        hostname: zm-db
        image: mariadb
        restart: always
        networks:
            - zoneminder
        volumes:
            - zm_db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=zm
        env_file:
            - ./.env

    zoneminder:
        container_name: zoneminder
        hostname: zoneminder
        build:
            context: ./zm
            args:
            ZM_VERSION: 1.36.4
            ES_VERSION: v6.1.25
        ipc: service:shmem
        restart: always
        stop_grace_period: 45s
        depends_on:
            - zm-db
        ports:
            - 8082:80
            - 8043:443
            - 9010:9000
        networks:
            - zoneminder
        volumes:
            - zm_data:/data
            - zm_config:/config
            - zm_log:/log
            # - type: tmpfs
            # target: /dev/shm
            # tmpfs:
            #     size: 1000000000
        env_file:
            - ./.env

    shmem:
        image: alpine:3.12
        command: sleep infinity
        shm_size: '2gb'
        ipc: shareable

    # logrotate:
    #     image: blacklabelops/logrotate:1.3
    #     environment:
    #         TZ: 'Europe/Moscow'
    #         LOGS_DIRECTORIES: '/var/log/zm'
    #         LOGROTATE_COMPRESSION: compress
    #         LOGROTATE_SIZE: 10M
    #     volumes:
    #         - ./.volumes/zm/logs:/var/log/zm


volumes:
  zm_db:
  zm_data:
  zm_config:
  zm_log:

networks:
  zoneminder: